### ISSUE TITLE
Robô Taxação FJP

### ISSUE THREAD

**Issue by Isabelle-Fernandes** [automatiza-mg/imersao-fjp#5]
## Descrição
A taxação dos professores da Fundação João Pinheiro (FJP) é realizada manualmente no SISAP. O objetivo da demanda é criar robô para efetuar os lançamentos de descontos de taxação no SISAP.

# Ações executadas:

## Visita in loco dia 15/05/2024

**Equipe DCD presente:** 
@gabrielbdornas, @augustacora, @henriquesiqr e @Isabelle-Fernandes

O servidor da FJP responsável pelos lançamentos explicou novamente para a equipe presente o fluxo de lançamento das taxações. 
Já havia robô feito da taxação. O objetivo da visita era para executar este robô. Contudo, durante a execução, o robô demonstrou erro e não foi possível sua execução. O problema maior que impactou a execução do robô foi a mudança da tela SISAP. Essa atualização do sistema impactou no passo a passo de execução do robô.

Foi explicado pela equipe nesse dia também a necessidade de obter o masp dos servidores ao invés de digitar o nome do servidor em tela SISAP.  

Servidor da FJP providenciou no mesmo dia de visita planilha interna que tinha a relação dos professores, tanto internos quanto externos, com respectivo masp.

Nesse dia, @gabrielbdornas dividiu a equipe em frentes de trabalho da seguinte forma:
- Augusta seria responsável pela execução robô e-mail.
- Henrique seria responsável pela execução robô Ponto Digital.
- Isabelle seria responsável pela execução robô taxação.

Restante do dia, cada um deu prosseguimento ao seu respectivo robô a fim de sanar os erros.

## Visita in loco dia 16/05/2024

**Equipe DCD presentes:** 
@gabrielbdornas, @augustacora, @henriquesiqr e @Isabelle-Fernandes

Equipe continuou com elaboração dos robôs.

O robô da taxação foi finalizado primeiro, pois entre os três, foi o que apresentou menos problemas. No mesmo dia ele foi executado e lançado os descontos de taxação dos servidores.

Foi informado ao servidor da FJP que o robô não estava taxando servidores que não dispunham de masp na planilha. Para estes, era necessária a taxação manual e providenciar o cadastro do masp tão logo quanto possível para que, no próximo mês de taxação, isso fosse sanado.

## Visita in loco dia 23/05/2024

**Equipe DCD presentes:** 
@augustacora, @henriquesiqr e @Isabelle-Fernandes

Quanto ao robô da taxação, foi acrescentado na rotina a inclusão automática dos masp's dos servidores na planilha de taxação. Isso havia sido feito manualmente na última visita para agilizar os lançamentos.

Servidora da FJP informou que o robô deixou de lançar taxação de alguns servidores no SISAP. Feito a conferência de quais servidores não tinham sido taxados, foi percebido que eram os mesmos que não tinham masp informado em planilha. Foi esclarecido que isso era esperado e informado no dia 16/05 ao servidor da FJP. Também, foi reiterado a necessidade da inclusão desses masp's faltantes antes da execução do robô. Caso contrário, para este caso, será necessário o lançamento manual.

Em um universo de aproximadamente 133 professores, aproximadamente 19 não foram taxados.

### Encaminhamentos:

- [x] Na visita do dia 23/05/2024 foi combinado da **equipe retornar à FJP** para esclarecimentos de dúvidas e explicar como executar o robô. Foi definido seria no início de junho/24, que é quando o servidor da FJP retornaria das férias.

## Visita in loco dia 06/06/2024

**Equipe DCD presentes:** 
@augustacora, @henriquesiqr e @Isabelle-Fernandes

Quanto ao robô da taxação, foi informado que a rotina de inclusão do masp não seria mais necessária, pois servidor GRH-FJP informou que isso seria feito por eles.

Houve a instalação do robô taxação, e-mail e Ponto-Digital na máquina da estação de trabalho da GRH-FJP onde ele será executado. 

A equipe DCD explicou como os robôs funcionam e executou cada um deles na máquina a ser utilizada.

Apenas o robô taxação apresentou erros de execução. Será necessário mais uma visita para sanar essa pendência. O erro apresentado foram dois:

- Erros de manipulação que o robô faz no arquivo Excel. Foi percebido que esse erro ocorre somente quando o robô não está mostrando a tela do Excel aberta. Quando, durante a execução do robô, o usuário força o Excel aparecer em primeiro plano, o robô não apresenta erro.
- Erro na escolha da admissão correta dos professores no SISAP.

### Encaminhamentos:
- [x] Sanar os erros apresentados pelo robô taxação.
- [x] Gravar um pequeno vídeo com o robô taxação funcionando.
- [x] Executar o robô taxação 100% rodando na máquina da estação de trabalho da GRH-FJP.
- [x] Elaborar post com instrução de utilização do robô no site Automatiza MG.

## Visita in loco dia 12/06/2024

**Equipe DCD presentes:** 
@augustacora, @henriquesiqr e @Isabelle-Fernandes

O robô foi instalado na na máquina da estação de trabalho da GRH-FJP onde ele será executado e realizada 100% das taxações. 

Durante a execução do robô, foram apresentados dois novos problemas e foram sanados no mesmo dia, editando o robô. São eles:

1. Um servidor estava com o formato de masp diferente dos demais e por isso, impediu o lançamento do SIAP. 
**Ação tomada**: acrescentou um fluxo no robô para formatar todos os masp's, colocando-os em padrão adequado para o lançamento no terminal Prodemge Sisap.

2. Na tela do terminal Prodemge Sisap apareceu uma tela a mais que não estava prevista no fluxo original. Essa tela consiste em uma mensagem de aviso, que não é mensal. Ela não ocorre com frequência, segundo servidor. Essa tela "a mais" altera o fluxo de ação do robô.
**Ação tomada**: acrescentou um fluxo no robô para enviar a tecla enter While determinada tela desejada não aparecesse. Dessa forma, caso a tela de mensagem apareça ou não no mês seguinte, não interferirá no processo de trabalho do robô.

Dessa forma o robô foi entregue, feito as últimas adaptações. Os servidores da área apresentaram insegurança para rodas os demais robores sozinhos. Manifestaram desejo da equipe estar presente para a execução do robô Ponto Digital e E-mail. É algo que a equipe precisa alinhar, pois mesmo depois de muitas visitas, ainda manifestam insegurança. 

### Encaminhamentos:
- [x] Equipe ou um integrante ao menos ir na FJP para rodar o robô Ponto Digital com a equipe na mesma semana.
- [x] Equipe ou um integrante ao menos ir na FJP para rodar o robô E-mail com a equipe na semana seguinte.

@YanVieira1905 

## Visita in loco dia 18/06/2024

**Equipe DCD presentes:** 
@augustacora, @henriquesiqr e @Isabelle-Fernandes

Visita teve como objetivo instalar e rodar o robô e-mail na máquina do servidor. Foi feito. Alguns problemas de adequação do robô a máquina surgiram e sanados no mesmo local. Para saber mais detalhes dessa visita, poderá encontrar com mais detalhes no **issue #4.**

### Encaminhamentos:
- [x] Agendar visita final na FJP para entrega do projeto. @YanVieira1905

**Comment by gabrielbdornas** [comment]
@Isabelle-Fernandes, ótimo seu relato. Parabéns!
